version: "3.8"

services:
  nginx:
    image: nginx:1.27.2-alpine
    container_name: pmt_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    command: ["nginx", "-g", "daemon off;"]
